# Building & releasing Electron w/ Travis https://studiolacosanostra.github.io/2019/03/26/Automate-electron-app-release-build-on-github-with-Travis-CI/
# Env variables for electron-builder codesigning https://www.electron.build/code-signing

language: node_js
node_js: "10"
os: osx
osx_image: xcode10.2

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder  

jobs:
  include:
    - stage: Test
      script:
        - yarn test
    - stage: Build Mac and Deploy to Github Release
      script:
        - yarn run build
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine

# before_deploy:
# # Codesign on Mac
# # https://www.update.rocks/blog/osx-signing-with-travis/
#   - if [ "$TRAVIS_OS_NAME" = osx ]; then chmod +x add-osx-cert.sh; fi
#   - if [ "$TRAVIS_OS_NAME" = osx ]; then ./scripts/add-osx-cert.sh; fi

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"