language: node_js
node_js: "10"

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
  
jobs:
  include:
    - stage: Test
      script:
        - yarn test
    - stage: Deploy Windows & Mac
      if: tag IS present # Only triggered if there is a Git tag for the version
      os: osx
      osx_image: xcode10.2
      script:
        - yarn run release --mac --win
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine

before_deploy:
# Codesign on Mac
# https://www.update.rocks/blog/osx-signing-with-travis/
  - if [ "$TRAVIS_OS_NAME" = osx ]; then chmod +x add-osx-cert.sh; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then ./scripts/add-osx-cert.sh; fi

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"