matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

jobs:
  include:
    - stage: Test
      script:
        - yarn test
    - stage: Deploy Windows & Mac
      if: tag IS present
      os: osx
      osx_image: xcode10.1
      script:
        - yarn run release --mac --win
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine

# Codesign on Mac
# https://www.update.rocks/blog/osx-signing-with-travis/
before_deploy:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then chmod +x add-osx-cert.sh; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then ./scripts/add-osx-cert.sh; fi

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"